"""
豆瓣 Top 250 电影列表
=====================
以英文名 + 中文名 + 年份 维护，用于 TMDB/RT/豆瓣 交叉匹配
"""

DOUBAN_TOP_250 = [
    # === 经典殿堂 ===
    {"title_en": "The Shawshank Redemption", "title_cn": "肖申克的救赎", "year": 1994},
    {"title_en": "Farewell My Concubine", "title_cn": "霸王别姬", "year": 1993},
    {"title_en": "Forrest Gump", "title_cn": "阿甘正传", "year": 1994},
    {"title_en": "Titanic", "title_cn": "泰坦尼克号", "year": 1997},
    {"title_en": "Spirited Away", "title_cn": "千与千寻", "year": 2001},
    {"title_en": "Léon: The Professional", "title_cn": "这个杀手不太冷", "year": 1994},
    {"title_en": "Life Is Beautiful", "title_cn": "美丽人生", "year": 1997},
    {"title_en": "Schindler's List", "title_cn": "辛德勒的名单", "year": 1993},
    {"title_en": "The Godfather", "title_cn": "教父", "year": 1972},
    {"title_en": "The Godfather: Part II", "title_cn": "教父2", "year": 1974},
    {"title_en": "12 Angry Men", "title_cn": "十二怒汉", "year": 1957},
    {"title_en": "The Dark Knight", "title_cn": "蝙蝠侠：黑暗骑士", "year": 2008},
    {"title_en": "Pulp Fiction", "title_cn": "低俗小说", "year": 1994},
    {"title_en": "The Silence of the Lambs", "title_cn": "沉默的羔羊", "year": 1991},
    {"title_en": "Fight Club", "title_cn": "搏击俱乐部", "year": 1999},
    {"title_en": "Se7en", "title_cn": "七宗罪", "year": 1995},
    {"title_en": "Saving Private Ryan", "title_cn": "拯救大兵瑞恩", "year": 1998},
    {"title_en": "Apocalypse Now", "title_cn": "现代启示录", "year": 1979},
    {"title_en": "The Matrix", "title_cn": "黑客帝国", "year": 1999},
    {"title_en": "Interstellar", "title_cn": "星际穿越", "year": 2014},

    # === 科幻 / 悬疑 ===
    {"title_en": "Inception", "title_cn": "盗梦空间", "year": 2010},
    {"title_en": "Blade Runner", "title_cn": "银翼杀手", "year": 1982},
    {"title_en": "2001: A Space Odyssey", "title_cn": "2001太空漫游", "year": 1968},
    {"title_en": "A Clockwork Orange", "title_cn": "发条橙", "year": 1971},
    {"title_en": "The Shining", "title_cn": "闪灵", "year": 1980},
    {"title_en": "Alien", "title_cn": "异形", "year": 1979},
    {"title_en": "Aliens", "title_cn": "异形2", "year": 1986},
    {"title_en": "The Truman Show", "title_cn": "楚门的世界", "year": 1998},
    {"title_en": "The Prestige", "title_cn": "致命魔术", "year": 2006},
    {"title_en": "Arrival", "title_cn": "降临", "year": 2016},
    {"title_en": "Dune", "title_cn": "沙丘", "year": 2021},
    {"title_en": "Dune: Part Two", "title_cn": "沙丘2", "year": 2024},
    {"title_en": "Ex Machina", "title_cn": "机械姬", "year": 2014},
    {"title_en": "Her", "title_cn": "她", "year": 2013},
    {"title_en": "Gravity", "title_cn": "地心引力", "year": 2013},

    # === 剧情 / 人文 ===
    {"title_en": "The Green Mile", "title_cn": "绿里奇迹", "year": 1999},
    {"title_en": "The Pursuit of Happyness", "title_cn": "当幸福来敲门", "year": 2006},
    {"title_en": "Good Will Hunting", "title_cn": "心灵捕手", "year": 1997},
    {"title_en": "A Beautiful Mind", "title_cn": "美丽心灵", "year": 2001},
    {"title_en": "The Pianist", "title_cn": "钢琴家", "year": 2002},
    {"title_en": "Cinema Paradiso", "title_cn": "天堂电影院", "year": 1988},
    {"title_en": "The Legend of 1900", "title_cn": "海上钢琴师", "year": 1998},
    {"title_en": "Hachi: A Dog's Tale", "title_cn": "忠犬八公的故事", "year": 2009},
    {"title_en": "The Intouchables", "title_cn": "触不可及", "year": 2011},
    {"title_en": "Django Unchained", "title_cn": "被解救的姜戈", "year": 2012},
    {"title_en": "Catch Me If You Can", "title_cn": "逍遥法外", "year": 2002},
    {"title_en": "The Departed", "title_cn": "无间道风云", "year": 2006},
    {"title_en": "Gladiator", "title_cn": "角斗士", "year": 2000},
    {"title_en": "The Curious Case of Benjamin Button", "title_cn": "返老还童", "year": 2008},
    {"title_en": "Flipped", "title_cn": "怦然心动", "year": 2010},
    {"title_en": "About Time", "title_cn": "时空恋旅人", "year": 2013},
    {"title_en": "The Secret Life of Walter Mitty", "title_cn": "白日梦想家", "year": 2013},
    {"title_en": "Green Book", "title_cn": "绿皮书", "year": 2018},
    {"title_en": "Scent of a Woman", "title_cn": "闻香识女人", "year": 1992},

    # === 动画 ===
    {"title_en": "WALL·E", "title_cn": "机器人总动员", "year": 2008},
    {"title_en": "Ratatouille", "title_cn": "美食总动员", "year": 2007},
    {"title_en": "Coco", "title_cn": "寻梦环游记", "year": 2017},
    {"title_en": "Zootopia", "title_cn": "疯狂动物城", "year": 2016},
    {"title_en": "Inside Out", "title_cn": "头脑特工队", "year": 2015},
    {"title_en": "Inside Out 2", "title_cn": "头脑特工队2", "year": 2024},
    {"title_en": "Soul", "title_cn": "心灵奇旅", "year": 2020},
    {"title_en": "Up", "title_cn": "飞屋环游记", "year": 2009},
    {"title_en": "Finding Nemo", "title_cn": "海底总动员", "year": 2003},
    {"title_en": "Toy Story 3", "title_cn": "玩具总动员3", "year": 2010},
    {"title_en": "Frozen", "title_cn": "冰雪奇缘", "year": 2013},
    {"title_en": "The Lion King", "title_cn": "狮子王", "year": 1994},
    {"title_en": "Monsters, Inc.", "title_cn": "怪兽电力公司", "year": 2001},
    {"title_en": "Howl's Moving Castle", "title_cn": "哈尔的移动城堡", "year": 2004},
    {"title_en": "My Neighbor Totoro", "title_cn": "龙猫", "year": 1988},
    {"title_en": "Princess Mononoke", "title_cn": "幽灵公主", "year": 1997},
    {"title_en": "Grave of the Fireflies", "title_cn": "萤火虫之墓", "year": 1988},
    {"title_en": "Spider-Man: Into the Spider-Verse", "title_cn": "蜘蛛侠：平行宇宙", "year": 2018},
    {"title_en": "The Iron Giant", "title_cn": "钢铁巨人", "year": 1999},
    {"title_en": "Your Name", "title_cn": "你的名字", "year": 2016},

    # === 华语电影 ===
    {"title_en": "In the Mood for Love", "title_cn": "花样年华", "year": 2000},
    {"title_en": "A Better Tomorrow", "title_cn": "英雄本色", "year": 1986},
    {"title_en": "Infernal Affairs", "title_cn": "无间道", "year": 2002},
    {"title_en": "To Live", "title_cn": "活着", "year": 1994},
    {"title_en": "Raise the Red Lantern", "title_cn": "大红灯笼高高挂", "year": 1991},
    {"title_en": "Chungking Express", "title_cn": "重庆森林", "year": 1994},
    {"title_en": "Spring in a Small Town", "title_cn": "小城之春", "year": 1948},
    {"title_en": "City of Life and Death", "title_cn": "南京!南京!", "year": 2009},
    {"title_en": "Let the Bullets Fly", "title_cn": "让子弹飞", "year": 2010},
    {"title_en": "Dying to Survive", "title_cn": "我不是药神", "year": 2018},
    {"title_en": "The Wandering Earth", "title_cn": "流浪地球", "year": 2019},

    # === 近年佳片 ===
    {"title_en": "Parasite", "title_cn": "寄生虫", "year": 2019},
    {"title_en": "Whiplash", "title_cn": "爆裂鼓手", "year": 2014},
    {"title_en": "La La Land", "title_cn": "爱乐之城", "year": 2016},
    {"title_en": "The Grand Budapest Hotel", "title_cn": "布达佩斯大饭店", "year": 2014},
    {"title_en": "Moonlight", "title_cn": "月光男孩", "year": 2016},
    {"title_en": "The Shape of Water", "title_cn": "水形物语", "year": 2017},
    {"title_en": "Nomadland", "title_cn": "无依之地", "year": 2020},
    {"title_en": "Everything Everywhere All at Once", "title_cn": "瞬息全宇宙", "year": 2022},
    {"title_en": "Oppenheimer", "title_cn": "奥本海默", "year": 2023},
    {"title_en": "Spider-Man: No Way Home", "title_cn": "蜘蛛侠：英雄无归", "year": 2021},
    {"title_en": "Top Gun: Maverick", "title_cn": "壮志凌云：独行侠", "year": 2022},
    {"title_en": "The Batman", "title_cn": "新蝙蝠侠", "year": 2022},
    {"title_en": "John Wick: Chapter 4", "title_cn": "疾速追杀4", "year": 2023},
    {"title_en": "Killers of the Flower Moon", "title_cn": "花月杀手", "year": 2023},
    {"title_en": "Barbie", "title_cn": "芭比", "year": 2023},
    {"title_en": "The Holdovers", "title_cn": "留校者联盟", "year": 2023},
    {"title_en": "Past Lives", "title_cn": "过往人生", "year": 2023},
    {"title_en": "Anatomy of a Fall", "title_cn": "坠落的审判", "year": 2023},
    {"title_en": "Poor Things", "title_cn": "可怜的东西", "year": 2023},
    {"title_en": "The Boy and the Heron", "title_cn": "苍鹭与少年", "year": 2023},

    # === 指环王 / 哈利波特 / 漫威 ===
    {"title_en": "The Lord of the Rings: The Fellowship of the Ring", "title_cn": "指环王：护戒使者", "year": 2001},
    {"title_en": "The Lord of the Rings: The Two Towers", "title_cn": "指环王：双塔奇兵", "year": 2002},
    {"title_en": "The Lord of the Rings: The Return of the King", "title_cn": "指环王：王者无敌", "year": 2003},
    {"title_en": "Harry Potter and the Sorcerer's Stone", "title_cn": "哈利·波特与魔法石", "year": 2001},
    {"title_en": "The Avengers", "title_cn": "复仇者联盟", "year": 2012},
    {"title_en": "Avengers: Endgame", "title_cn": "复仇者联盟4：终局之战", "year": 2019},
    {"title_en": "Guardians of the Galaxy", "title_cn": "银河护卫队", "year": 2014},
    {"title_en": "Iron Man", "title_cn": "钢铁侠", "year": 2008},

    # === 印度 / 其他国家 ===
    {"title_en": "3 Idiots", "title_cn": "三傻大闹宝莱坞", "year": 2009},
    {"title_en": "Dangal", "title_cn": "摔跤吧！爸爸", "year": 2016},
    {"title_en": "Amélie", "title_cn": "天使爱美丽", "year": 2001},
    {"title_en": "The Lives of Others", "title_cn": "窃听风暴", "year": 2006},
    {"title_en": "Pan's Labyrinth", "title_cn": "潘神的迷宫", "year": 2006},
    {"title_en": "Oldboy", "title_cn": "老男孩", "year": 2003},
]
